// Package irl provides a Go client for the IRL Engine API.
//
// The IRL Engine seals every AI trading decision with a cryptographic
// reasoning trace before the order reaches the exchange. This client
// covers the full API surface: Authorize (pre-trade), Bind (post-fill),
// GetTrace (audit replay), agent management, trace queries, and admin
// endpoints.
//
// Usage:
//
//	client, err := irl.NewClient(irl.Config{
//	    BaseURL:  "https://irl.example.com",
//	    APIToken: os.Getenv("IRL_API_TOKEN"),
//	})
//	if err != nil {
//	    log.Fatal(err)
//	}
//
//	resp, err := client.Authorize(ctx, irl.AuthorizeRequest{ ... })
package irl

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"time"
)

// ─── Config ──────────────────────────────────────────────────────────────────

// Config holds the connection parameters for the IRL Engine client.
type Config struct {
	// BaseURL is the IRL Engine API root, e.g. "https://irl.example.com".
	BaseURL string

	// APIToken is the bearer token issued by IRL Engine at agent registration.
	APIToken string

	// Timeout for individual HTTP requests. Default: 5 seconds.
	Timeout time.Duration

	// mTLS fields — optional. Leave nil for token-only auth.
	// CertFile and KeyFile are paths to the client cert and private key PEM files.
	CertFile string
	KeyFile  string
	// CAFile is the path to the CA cert PEM used to verify the server cert.
	CAFile string
}

// ─── Errors ───────────────────────────────────────────────────────────────────

// APIError is returned when the IRL Engine responds with a non-2xx status.
type APIError struct {
	StatusCode int
	ErrorCode  string `json:"error"`
	Message    string `json:"message"`
}

func (e *APIError) Error() string {
	return fmt.Sprintf("IRL API %d %s: %s", e.StatusCode, e.ErrorCode, e.Message)
}

// ─── Request / Response types ─────────────────────────────────────────────────

// TradeAction encodes a trade direction in the serde enum format required by the server.
//
// Usage:
//   LongAction(2.0)        → {"Long": 2.0}
//   ShortAction(1.5)       → {"Short": 1.5}
//   NeutralAction()        → "Neutral"
//   CustomAction("Buy")    → {"Custom": "Buy"}
type TradeAction interface{}

// LongAction returns a TradeAction for a long/buy position.
func LongAction(quantity float64) TradeAction { return map[string]float64{"Long": quantity} }

// ShortAction returns a TradeAction for a short/sell position.
func ShortAction(quantity float64) TradeAction { return map[string]float64{"Short": quantity} }

// NeutralAction returns a TradeAction for a flat/neutral position change.
func NeutralAction() TradeAction { return "Neutral" }

// CustomAction wraps an exchange-specific action string (e.g. "Buy", "Open Long").
func CustomAction(s string) TradeAction { return map[string]string{"Custom": s} }

// AuthorizeRequest is the payload for POST /irl/authorize.
type AuthorizeRequest struct {
	AgentID                string      `json:"agent_id"`
	ModelID                string      `json:"model_id"`
	ModelHashHex           string      `json:"model_hash_hex"`
	PromptVersion          string      `json:"prompt_version"`
	FeatureSchemaID        string      `json:"feature_schema_id"`
	HyperparameterChecksum string      `json:"hyperparameter_checksum"`
	// Action must be built using LongAction, ShortAction, NeutralAction, or CustomAction.
	Action                 TradeAction `json:"action"`
	Asset                  string      `json:"asset"`
	Quantity               float64     `json:"quantity"`
	Notional               float64     `json:"notional"`
	NotionalCurrency       string      `json:"notional_currency,omitempty"` // default "USD"
	Multiplier             float64     `json:"multiplier,omitempty"`        // default 1.0
	OrderType              string      `json:"order_type"`
	VenueID                string      `json:"venue_id"`
	AgentValidTime         int64       `json:"agent_valid_time"` // Unix ms
	LimitPrice             *float64    `json:"limit_price,omitempty"`
	StopPrice              *float64    `json:"stop_price,omitempty"`
	ClientOrderID          *string     `json:"client_order_id"` // required; generated by Authorize when nil
	ReduceOnly             bool        `json:"reduce_only"`
	Heartbeat              interface{} `json:"heartbeat,omitempty"`
	Regulatory             interface{} `json:"regulatory,omitempty"`
}

// AuthorizeResponse is returned by POST /irl/authorize on success.
type AuthorizeResponse struct {
	TraceID       string `json:"trace_id"`
	ReasoningHash string `json:"reasoning_hash"`
	Authorized    bool   `json:"authorized"`
	ShadowBlocked bool   `json:"shadow_blocked"`
}

// BindRequest is the payload for POST /irl/bind-execution.
type BindRequest struct {
	TraceID          string   `json:"trace_id"`
	ExchangeTxID     string   `json:"exchange_tx_id"`
	ExecutionStatus  string   `json:"execution_status"`            // "Filled" | "Rejected" | "Partial"
	ExecutionPrice   *float64 `json:"execution_price,omitempty"`   // optional fill price
	ExecutedQuantity *float64 `json:"executed_quantity,omitempty"` // optional, for divergence detection
	ExecutionTime    *int64   `json:"execution_time_ms,omitempty"` // optional Unix ms of exchange confirmation
	ExecutedSide     *string  `json:"executed_side,omitempty"`     // optional "Long" | "Short", verified against intent
	Asset            *string  `json:"asset,omitempty"`             // optional, triggers asset-mismatch check
}

// BindResponse is returned by POST /irl/bind-execution on success.
type BindResponse struct {
	TraceID            string  `json:"trace_id"`
	FinalProof         *string `json:"final_proof,omitempty"`
	VerificationStatus string  `json:"verification_status"`
	ExecutionStatus    *string `json:"execution_status,omitempty"`
	DivergenceReason   *string `json:"divergence_reason,omitempty"`
}

// TraceResponse is returned by GET /irl/trace/:trace_id.
type TraceResponse struct {
	TraceID       string          `json:"trace_id"`
	ReasoningHash string          `json:"reasoning_hash"`
	Trace         json.RawMessage `json:"trace"`
}

// AgentProfile is returned by agent management endpoints.
type AgentProfile struct {
	ID             string  `json:"agent_id"`
	Name           string  `json:"name"`
	ModelHashHex   string  `json:"model_hash_hex"`
	Status         string  `json:"status"`
	MaxNotional    float64 `json:"max_notional"`
	AllowedRegimes []int   `json:"allowed_regimes,omitempty"`
	CreatedAt      string  `json:"created_at,omitempty"` // not returned by IRL v1.3.0
}

// RegisterAgentRequest is the payload for POST /irl/agents.
type RegisterAgentRequest struct {
	Name           string  `json:"name"`
	ModelHashHex   string  `json:"model_hash_hex"`
	MaxNotional    float64 `json:"max_notional"`
	AllowedRegimes []int   `json:"allowed_regimes,omitempty"`
}

// TraceListParams are optional filters for GET /irl/traces.
type TraceListParams struct {
	AgentID string // filter by agent UUID
	From    int64  // Unix ms, start of range
	To      int64  // Unix ms, end of range
	Status  string // PENDING|MATCHED|DIVERGENT|ORPHAN|EXPIRED|SHADOW_HALTED
	Limit   int    // default 500, max 5000
}

// TraceListResponse is returned by GET /irl/traces, /irl/pending, /irl/orphans, and /irl/shadow-violations.
type TraceListResponse struct {
	Count  int               `json:"count"`
	Traces []json.RawMessage `json:"traces"`
}

// HealthResponse is returned by GET /irl/health.
type HealthResponse struct {
	Status string `json:"status"`
}

// ─── Client ───────────────────────────────────────────────────────────────────

// Client is a thread-safe IRL Engine API client.
type Client struct {
	cfg        Config
	httpClient *http.Client
}

// NewClient constructs a new IRL Engine client. Returns an error if the mTLS
// configuration is invalid (cert/key file unreadable or mismatched).
func NewClient(cfg Config) (*Client, error) {
	if cfg.Timeout == 0 {
		cfg.Timeout = 5 * time.Second
	}

	transport := &http.Transport{}

	if cfg.CertFile != "" || cfg.KeyFile != "" {
		// mTLS: load client cert
		cert, err := tls.LoadX509KeyPair(cfg.CertFile, cfg.KeyFile)
		if err != nil {
			return nil, fmt.Errorf("irl: load client cert: %w", err)
		}

		tlsCfg := &tls.Config{
			Certificates: []tls.Certificate{cert},
		}

		if cfg.CAFile != "" {
			caPEM, err := os.ReadFile(cfg.CAFile)
			if err != nil {
				return nil, fmt.Errorf("irl: read CA cert: %w", err)
			}
			pool := x509.NewCertPool()
			if !pool.AppendCertsFromPEM(caPEM) {
				return nil, fmt.Errorf("irl: invalid CA cert PEM in %s", cfg.CAFile)
			}
			tlsCfg.RootCAs = pool
		}

		transport.TLSClientConfig = tlsCfg
	}

	return &Client{
		cfg: cfg,
		httpClient: &http.Client{
			Timeout:   cfg.Timeout,
			Transport: transport,
		},
	}, nil
}

// ─── Core methods ─────────────────────────────────────────────────────────────

// Authorize sends a pre-trade intent to the IRL Engine for regime verification
// and cryptographic sealing. Returns the trace_id and reasoning_hash on success.
//
// On policy violation (regime block, notional limit) the engine returns HTTP 403
// and this method returns an *APIError with the appropriate error code.
func (c *Client) Authorize(ctx context.Context, req AuthorizeRequest) (*AuthorizeResponse, error) {
	// venue_id and client_order_id are required by the server (422 if missing).
	if req.VenueID == "" {
		return nil, fmt.Errorf("irl: VenueID is required (e.g. \"BINANCE\")")
	}
	if req.ClientOrderID == nil {
		buf := make([]byte, 16)
		if _, err := rand.Read(buf); err != nil {
			return nil, fmt.Errorf("irl: generate client_order_id: %w", err)
		}
		id := "irl-" + hex.EncodeToString(buf)
		req.ClientOrderID = &id
	}
	var resp AuthorizeResponse
	if err := c.post(ctx, "/irl/authorize", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Bind records the exchange execution outcome for a previously authorized trade.
// The trace is updated with the fill price and execution status, and a final_proof
// is computed as SHA-256(reasoning_hash || exchange_tx_id).
//
// Bind must be called within the trace expiry window (default: 1 hour,
// configurable via TRACE_EXPIRY_MS).
func (c *Client) Bind(ctx context.Context, req BindRequest) (*BindResponse, error) {
	var resp BindResponse
	if err := c.post(ctx, "/irl/bind-execution", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetTrace fetches the full cryptographic reasoning trace for audit replay.
// The trace_json returned has been decrypted server-side if at-rest encryption
// is enabled (KMS_PROVIDER != none).
func (c *Client) GetTrace(ctx context.Context, traceID string) (*TraceResponse, error) {
	var resp TraceResponse
	if err := c.get(ctx, "/irl/trace/"+traceID, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ─── Health ───────────────────────────────────────────────────────────────────

// Health checks liveness. GET /irl/health — no Authorization required.
func (c *Client) Health(ctx context.Context) (*HealthResponse, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.cfg.BaseURL+"/irl/health", nil)
	if err != nil {
		return nil, fmt.Errorf("irl: build request: %w", err)
	}
	var resp HealthResponse
	return &resp, c.do(req, &resp)
}

// ─── Agent management ─────────────────────────────────────────────────────────

// RegisterAgent registers a new agent in the Multi-Agent Registry.
// POST /irl/agents
func (c *Client) RegisterAgent(ctx context.Context, req RegisterAgentRequest) (*AgentProfile, error) {
	var resp AgentProfile
	if err := c.post(ctx, "/irl/agents", req, &resp); err != nil {
		return nil, err
	}
	// The register response is {agent_id, model_hash_hex, status}; fill the rest
	// from the request.
	resp.Name = req.Name
	resp.MaxNotional = req.MaxNotional
	resp.AllowedRegimes = req.AllowedRegimes
	return &resp, nil
}

// ListAgents returns all registered agents.
// GET /irl/agents
func (c *Client) ListAgents(ctx context.Context) ([]AgentProfile, error) {
	var raw struct {
		Agents []AgentProfile `json:"agents"`
	}
	return raw.Agents, c.get(ctx, "/irl/agents", &raw)
}

// GetAgent returns a single agent profile by UUID.
// GET /irl/agents/:id
func (c *Client) GetAgent(ctx context.Context, agentID string) (*AgentProfile, error) {
	var resp AgentProfile
	return &resp, c.get(ctx, "/irl/agents/"+agentID, &resp)
}

// UpdateAgentStatus changes an agent's status.
// status: "Active" | "Suspended" | "Deregistered"
// PATCH /irl/agents/:id/status
func (c *Client) UpdateAgentStatus(ctx context.Context, agentID, status string) error {
	return c.patch(ctx, "/irl/agents/"+agentID+"/status", map[string]string{"status": status}, nil)
}

// SuspendAgent is a convenience wrapper around UpdateAgentStatus.
func (c *Client) SuspendAgent(ctx context.Context, agentID string) error {
	return c.UpdateAgentStatus(ctx, agentID, "Suspended")
}

// ActivateAgent is a convenience wrapper around UpdateAgentStatus.
func (c *Client) ActivateAgent(ctx context.Context, agentID string) error {
	return c.UpdateAgentStatus(ctx, agentID, "Active")
}

// ─── Trace queries ────────────────────────────────────────────────────────────

// ListPending returns PENDING traces older than ageSeconds.
// GET /irl/pending
func (c *Client) ListPending(ctx context.Context, ageSeconds int) (*TraceListResponse, error) {
	var resp TraceListResponse
	return &resp, c.get(ctx, fmt.Sprintf("/irl/pending?age_seconds=%d", ageSeconds), &resp)
}

// ListOrphans returns DIVERGENT and EXPIRED traces.
// GET /irl/orphans
func (c *Client) ListOrphans(ctx context.Context) (*TraceListResponse, error) {
	var resp TraceListResponse
	return &resp, c.get(ctx, "/irl/orphans", &resp)
}

// GetShadowViolations returns traces where shadow mode intercepted a policy violation.
// GET /irl/shadow-violations
func (c *Client) GetShadowViolations(ctx context.Context) (*TraceListResponse, error) {
	var resp TraceListResponse
	return &resp, c.get(ctx, "/irl/shadow-violations", &resp)
}

// ListTraces returns a filtered, paginated list of reasoning traces.
// All params in TraceListParams are optional.
// GET /irl/traces
func (c *Client) ListTraces(ctx context.Context, params TraceListParams) (*TraceListResponse, error) {
	u := c.cfg.BaseURL + "/irl/traces"
	sep := "?"
	add := func(k, v string) { u += sep + k + "=" + v; sep = "&" }
	if params.AgentID != "" {
		add("agent_id", params.AgentID)
	}
	if params.From != 0 {
		add("from", fmt.Sprintf("%d", params.From))
	}
	if params.To != 0 {
		add("to", fmt.Sprintf("%d", params.To))
	}
	if params.Status != "" {
		add("status", params.Status)
	}
	if params.Limit > 0 {
		add("limit", fmt.Sprintf("%d", params.Limit))
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, fmt.Errorf("irl: build request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+c.cfg.APIToken)
	var resp TraceListResponse
	return &resp, c.do(req, &resp)
}

// ─── Admin endpoints (owner-level token required) ─────────────────────────────

// GetShadowMode returns the current shadow mode state.
// GET /irl/admin/shadow-mode
func (c *Client) GetShadowMode(ctx context.Context) (map[string]interface{}, error) {
	var resp map[string]interface{}
	return resp, c.get(ctx, "/irl/admin/shadow-mode", &resp)
}

// SetShadowMode enables or disables shadow mode.
// POST /irl/admin/shadow-mode
func (c *Client) SetShadowMode(ctx context.Context, enabled bool, reason string) (map[string]interface{}, error) {
	body := map[string]interface{}{"enabled": enabled}
	if reason != "" {
		body["reason"] = reason
	}
	var resp map[string]interface{}
	return resp, c.post(ctx, "/irl/admin/shadow-mode", body, &resp)
}

// GetAuditLog returns a paginated admin audit log.
// Pass beforeID as a cursor from the previous response for pagination.
// GET /irl/admin/audit-log
func (c *Client) GetAuditLog(ctx context.Context, action, targetID, beforeID string, limit int) (map[string]interface{}, error) {
	u := c.cfg.BaseURL + "/irl/admin/audit-log"
	sep := "?"
	add := func(k, v string) { u += sep + k + "=" + v; sep = "&" }
	if action != "" {
		add("action", action)
	}
	if targetID != "" {
		add("target_id", targetID)
	}
	if beforeID != "" {
		add("before_id", beforeID)
	}
	if limit > 0 {
		add("limit", fmt.Sprintf("%d", limit))
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, fmt.Errorf("irl: build request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+c.cfg.APIToken)
	var resp map[string]interface{}
	return resp, c.do(req, &resp)
}

// GDPRErase nullifies PII in all reasoning traces for the given agent (GDPR Art. 17).
// Requires KMS_PROVIDER configured on the server.
// POST /irl/admin/gdpr-erase/:agent_id
func (c *Client) GDPRErase(ctx context.Context, agentID string) (map[string]interface{}, error) {
	var resp map[string]interface{}
	return resp, c.post(ctx, "/irl/admin/gdpr-erase/"+agentID, struct{}{}, &resp)
}

// IssueToken issues a new client-role API token (returned exactly once).
// Save the token immediately — it is never stored on the server.
// POST /irl/admin/tokens
func (c *Client) IssueToken(ctx context.Context, clientName string) (map[string]interface{}, error) {
	var resp map[string]interface{}
	return resp, c.post(ctx, "/irl/admin/tokens", map[string]string{"client_name": clientName}, &resp)
}

// RevokeToken revokes a token by its 12-character token_id prefix.
// DELETE /irl/admin/tokens/:token_id
func (c *Client) RevokeToken(ctx context.Context, tokenID string) (map[string]interface{}, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, c.cfg.BaseURL+"/irl/admin/tokens/"+tokenID, nil)
	if err != nil {
		return nil, fmt.Errorf("irl: build request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+c.cfg.APIToken)
	var resp map[string]interface{}
	return resp, c.do(req, &resp)
}

// ─── Static utilities ─────────────────────────────────────────────────────────

// ComputeModelHash returns the SHA-256 hex digest of a model configuration map.
// Keys are sorted before hashing, matching Python's json.dumps(sort_keys=True)
// and the TypeScript implementation. Register this hash in the Multi-Agent Registry
// and pass it as ModelHashHex in AuthorizeRequest.
//
// Example:
//
//	hash, err := irl.ComputeModelHash(map[string]interface{}{
//	    "model":   "hmm-v3.1",
//	    "version": "1.0",
//	})
func ComputeModelHash(config map[string]interface{}) (string, error) {
	keys := make([]string, 0, len(config))
	for k := range config {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	canonical := "{"
	for i, k := range keys {
		vb, err := json.Marshal(config[k])
		if err != nil {
			return "", fmt.Errorf("irl: compute model hash: %w", err)
		}
		kb, _ := json.Marshal(k)
		if i > 0 {
			canonical += ","
		}
		canonical += string(kb) + ":" + string(vb)
	}
	canonical += "}"

	sum := sha256.Sum256([]byte(canonical))
	return fmt.Sprintf("%x", sum), nil
}

// ─── HTTP helpers ─────────────────────────────────────────────────────────────

func (c *Client) post(ctx context.Context, path string, body, out interface{}) error {
	buf, err := json.Marshal(body)
	if err != nil {
		return fmt.Errorf("irl: marshal request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.cfg.BaseURL+path, bytes.NewReader(buf))
	if err != nil {
		return fmt.Errorf("irl: build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.cfg.APIToken)

	return c.do(req, out)
}

func (c *Client) get(ctx context.Context, path string, out interface{}) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.cfg.BaseURL+path, nil)
	if err != nil {
		return fmt.Errorf("irl: build request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+c.cfg.APIToken)

	return c.do(req, out)
}

func (c *Client) patch(ctx context.Context, path string, body, out interface{}) error {
	buf, err := json.Marshal(body)
	if err != nil {
		return fmt.Errorf("irl: marshal request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPatch, c.cfg.BaseURL+path, bytes.NewReader(buf))
	if err != nil {
		return fmt.Errorf("irl: build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.cfg.APIToken)

	return c.do(req, out)
}

func (c *Client) do(req *http.Request, out interface{}) error {
	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("irl: http: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("irl: read body: %w", err)
	}

	if resp.StatusCode >= 400 {
		apiErr := &APIError{StatusCode: resp.StatusCode}
		_ = json.Unmarshal(body, apiErr)
		return apiErr
	}

	if out != nil && len(body) > 0 {
		if err := json.Unmarshal(body, out); err != nil {
			return fmt.Errorf("irl: decode response: %w", err)
		}
	}
	return nil
}
